version: '3.7'

services: 
    client:
        container_name: client
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
    server:
        container_name: server
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "4000:4000"