name: Build and deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # This workflow contains a single job called "build and deploy"
  test:
    name: Test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      DATABASE: ${{secrets.DATABASE}}
      NODE_ENV: ${{secrets.NODE_ENV}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          cd server
          npm install
          npm run setup_db_test
          npm run test
    
  deploy:
      name: Deploy
      runs-on: ubuntu-latest
      needs: test

      steps: 
        - name: Checkout
          uses: actions/checkout@v1

        - name: Add remote origin
          run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git

        - name: Deploy backend to heroku
          run: git push heroku `git subtree split --prefix server master`:master --force